# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java
env: flex

handlers:
- url: /.*
  script: auto

instance_class: F2

automatic_scaling:
  max_num_instances: 1

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "17"

env_variables:
  SPRING_PROFILES_ACTIVE: 'dev'
  MONGODB_PASSWORD: MONGO_PLACEHOLDER
  API_KEY: API_PLACEHOLDER

